### ISSUE TITLE
Browse components by type

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#1]
We plan to build a menu grouping components by type

**Comment by raphaelfournier** [comment]
Done for WP and Pilot. See: def0e1d.

Should be done also by using the "type" from schema (to group components in "categories").

**Comment by raphaelfournier** [comment]
The improved welcome page (see #20) is listing components organized by "type". We need to think if it's necessary to have this in the sidebar. If not, the issue can probably be closed, and the work continue in #20.

**Comment by enridaga** [comment]
We still need to group the components at the bottom of the WP and Pilot pages

**Comment by raphaelfournier** [comment]
This issue seems now very close to #22…

To do:
- re-use the code from the "welcome" page (see 3fba5e37)

**Comment by raphaelfournier** [comment]
Mentioned by @marilenadaquino in TB meeting.

**Comment by raphaelfournier** [comment]
Next action:
- grab the code from Home and implement it in WP and Pilot pages @raphaelfournier
