### ISSUE TITLE
Per page "Table of content"

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#14]
Useful to have a TOC at the top of .md pages (e.g. Rulebook)

**Comment by enridaga** [comment]
@raphaelfournier suggests https://pmarsceill.github.io/just-the-docs/docs/ui-components

**Comment by raphaelfournier** [comment]
In fact, it's harder than it looks: it's not possible to use the `:toc` directive in a layout, it has to be manually added to each markdown page. No feasible at Polifonia's scale. See: https://github.com/pmarsceill/just-the-docs/issues/625
So I am considering a JavaScript script to perform this inpage-toc.

**Comment by raphaelfournier** [comment]
Commit eebc918 is an attempt (for stories). It's working, sticky, but not at the right place in the page.
