### ISSUE TITLE
Is `_data/wps.yml` any useful?

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#19]
Just a question

**Comment by raphaelfournier** [comment]
Currently, the tags page (`pages/tags.md`) uses it, as follows (line 12):
```
{% for wp in site.data.wps %}
```
(same for pilots line 24)

However, now that we have pilots/wps pages in `pages/pilots/`, I think the implementation of the tag page could change, we don't need 2 systems for looping over the list of wp/pilots.

**Comment by raphaelfournier** [comment]
The action on this is: 
- change the implementation in the tags.md page
- remove the files
- close the issue.

**Comment by raphaelfournier** [comment]
Commit 048b298 fixes it, the tags page was rewritten. 

Could be improved with different names for the links (eg, several "Sonia" stories appear for WP2, referring to different pages). And the layout could use bullet lists.
