### ISSUE TITLE
Polifonia OCR

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#45]

**Comment by enridaga** [comment]
Please add at least the Title and short paragraph description to related .md file.
Please make sure that the Title is the same as the (readable) schema annotation `name`.

**Comment by enridaga** [comment]
Specifically, change `# Polifonia OCR` to `# Textual Corpus Population` in the readme.md

**Comment by andreamust** [comment]
Thank you Enrico for the clarification. I updated main title of the README.md to `# Textual Corpus Population`.
