### ISSUE TITLE
Neuma search engine

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#47]

**Comment by enridaga** [comment]
Please add at least the Title and short paragraph description to related .md file.
Please make sure that the Title is the same as the (readable) schema annotation `name`.

**Comment by raphaelfournier** [comment]
Done for the Neuma/FACETS search engine.
See commits 
- https://github.com/polifonia-project/facets-search-engine/commit/c6f20c147ecda07fb3134a5cebdbf04c16196ea6
- https://github.com/polifonia-project/facets-search-engine/commit/1a364b8c3eb9356edf74b301e89c71fb287d0d9d
