### ISSUE TITLE
Documentation: how to build the ecosystem website?

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#5]
Update the README with basic information for developers on how to rebuild the website and how to run locally (e.g. updating references to submodules, run script, ...)

**Comment by raphaelfournier** [comment]
A first procedure was added on the README page. 
@enridaga please try it when you have time and let me know if it works for you.

**Comment by raphaelfournier** [comment]
Currently, it works for @enridaga and myself. I close the issue, we may re-open if someone wants to contribute and experiments problems.
