### ISSUE TITLE
Collect & prepare repositories to include in v1.1

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#50]
Please comment on this issue with repositories to be included.

**Comment by marilenadaquino** [comment]
WP1.T3 repos

 * musow web app and dataset https://github.com/polifonia-project/registry_app
 * clef https://github.com/polifonia-project/clef
 * melody https://github.com/polifonia-project/dashboard
 * web portal materials and mockups https://github.com/polifonia-project/web_portal

**Comment by jmmcd** [comment]
WP3:

* Folk n-gram analysis (software) https://github.com/polifonia-project/folk_ngram_analysis
* Root-note detection (software) https://github.com/polifonia-project/folk_ngram_analysis/tree/master/root_note_detection
* *Ceol Rince na h-Éireann* (corpus) https://github.com/polifonia-project/folk_ngram_analysis/tree/master/corpus
* Local Harmonic Agreement based on Recurrent Patterns https://github.com/polifonia-project/harmonic-similarity 



@jonnybluesman @andreamust I've included LHARP above as it was a component in D3.1, please correct me if needed.

**Comment by jonnybluesman** [comment]
@enridaga  https://github.com/polifonia-project/lharp is the right one, so we should be good already!

**Comment by enridaga** [comment]
Also to add:

- meetups_pilot
- polifonia_lexicon
- musow_pipeline?

**Comment by enridaga** [comment]
This is done, preparing release
