### ISSUE TITLE
Github repositories versus Zenodo back-up's

### ISSUE THREAD

**Issue by AndreaMargit** [polifonia-project/ecosystem#57]
Dear Raphael, is there a way to see which of the 61 Github repositories actually used the GitHub to zenodo pipeline and have now an appearance in Zenodo? Not all of them are probably in the Zenodo community.

**Comment by raphaelfournier** [comment]
Currently, no. We should probably update the schema to add a "zenodo field" to track this. Unless there's the possibility to ckeck automatically some urls, which would avoid requiring user input.

**Comment by enridaga** [comment]
Zenodo integration is being discussed in https://github.com/reeco-framework/reeco-jekyll/issues/20
