### ISSUE TITLE
Add repositories for MEETUPS pilot

### ISSUE THREAD

**Issue by albamoralest** [polifonia-project/ecosystem#58]
For MEETUPS we have two more repositories:
The knowledge graph
- polifonia-project/meetups-knowledge-graph:tag:v0.2
The ontology
- polifonia-project/meetups-ontology:tag:v0.1

**Comment by JaseMK** [comment]
please also add 'meetups-application', which is where I'm developing the UI demo.

**Comment by JaseMK** [comment]
also 'meetups-ui-design'
