### ISSUE TITLE
Missing component: MusicBO Knowledge Graph

### ISSUE THREAD

**Issue by arianna-graciotti** [polifonia-project/ecosystem#73]
Hello,

This issue is for allowing the inclusion of the MusicBO KG in the Polifonia Ecosystem Website.

These are the details related to MusicBO Knowledge Graph:

Title: MusicBO Knowledge Graph

Subtitle: The Knowledge Graph about the role of Bologna in the European musical landscape.
Type of the output: Knowledge Graph
Names of people that worked on it: Arianna Graciotti, Valentina Carriero, Rocco Tripodi, Eleonora Marzi, Fiorela Ciroku
Description: MusicBO Knowledge Graph stores information about the role of music in the city of Bologna from a historical and social perspective. It aims to satisfy the requirements of MusicBO pilot use case, namely conveying knowledge about music performances in Bologna and encounters between musicians, composers, critics and historians who passed through Bologna.
GitHub Repo Link: https://github.com/polifonia-project/musicbo-knowledge-graph SPARQL endpoint link: https://polifonia.disi.unibo.it/musicbo/sparql
MELODY data story link: https://projects.dharc.unibo.it/melody/musicbo/music_in_bologna_knowledge_graph_overview

<br class="Apple-interchange-newline">Title

MusicBO Knowledge Graph

Subtitle

The Knowledge Graph about the role of Bologna in the European musical landscape.

Type of the output

Knowledge Graph

Names of people that worked on it

Arianna Graciotti, Valentina Carriero, Rocco Tripodi, Eleonora Marzi, Fiorela Ciroku

Description

MusicBO Knowledge Graph stores information about the role of music in the city of Bologna from a historical and social perspective. It aims to satisfy the requirements of MusicBO pilot use case, namely conveying knowledge about music performances in Bologna and encounters between musicians, composers, critics and historians who passed through Bologna.

Link

[https://github.com/polifonia-project/musicbo-knowledge-graph; https://polifonia.disi.unibo.it/musicbo/sparql](https://github.com/polifonia-project/musicbo-knowledge-graph;%20https:/polifonia.disi.unibo.it/musicbo/sparql)
Please, let me and @EleonoraMarzi if this information is enough.

Thanks,

Arianna

**Comment by enridaga** [comment]
Thanks, Arianna, we only need to know the repository, if the annotations are there, the rest is automated.
